- name: Copy source
  copy:
    src: '{{ inventory_dir }}/website'
    dest: '{{ www_root }}/{{ app_name }}/'
    owner: marlon
    group: www-data
  become: True

- name: Copy docker source
  template:
    src: '{{ role_path }}/templates/docker-compose.yaml.j2'
    dest: '{{ www_root }}/{{ app_name }}/docker-compose.yaml'
    owner: marlon
    group: www-data
  become: True